//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Информационое_приложение
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ИнформационаяБазаEntities : DbContext
    {
        static private ИнформационаяБазаEntities IBE = null;

        static public ИнформационаяБазаEntities GetИнформационаяБазаEntities()
        {
            if (IBE == null)
                IBE = new ИнформационаяБазаEntities();

            return IBE;
        }

        public ИнформационаяБазаEntities()
            : base("name=ИнформационаяБазаEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Задания> Задания { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Отрасли> Отрасли { get; set; }
        public virtual DbSet<ПодЗадачи> ПодЗадачи { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<СписокИсполнителей> СписокИсполнителей { get; set; }
        public virtual DbSet<Статусы> Статусы { get; set; }
    }
}
