//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Информационое_приложение
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПодЗадачи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПодЗадачи()
        {
            this.СписокИсполнителей = new HashSet<СписокИсполнителей>();
        }
    
        public int КодПодЗадачи { get; set; }
        public string Название { get; set; }
        public int СтатусПодЗадание { get; set; }
        public string КомментарийПодЗадание { get; set; }
    
        public virtual Статусы Статусы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписокИсполнителей> СписокИсполнителей { get; set; }
    }
}
